from pathlib import Path

from PySide6.QtCore import Qt
from PySide6.QtWidgets import (QFrame, QFormLayout, QGridLayout, QHBoxLayout, QLabel,
    QLineEdit, QScrollArea, QSpinBox, QTextEdit, QToolButton, QVBoxLayout, QWidget)


def build_settings(window):
    from .window import button
    from ..workbench import work_root

    page = QWidget()
    page.setObjectName("SettingsPage")
    layout = QVBoxLayout(page)
    layout.setContentsMargins(24, 20, 24, 18)
    layout.setSpacing(10)
    title = QLabel("设置")
    title.setObjectName("Title")
    subtitle = QLabel("管理资料与备份存放位置。日常使用通常只需要检查这两处。")
    subtitle.setObjectName("Subtitle")
    layout.addWidget(title)
    layout.addWidget(subtitle)

    def card(title_text, hint, icon):
        frame = QFrame()
        frame.setObjectName("SettingsCard")
        outer = QVBoxLayout(frame)
        outer.setContentsMargins(18, 15, 18, 16)
        outer.setSpacing(12)
        header = QHBoxLayout()
        badge = QLabel(icon)
        badge.setObjectName("SettingsIcon")
        badge.setAlignment(Qt.AlignmentFlag.AlignCenter)
        badge.setFixedSize(48, 48)
        header.addWidget(badge)
        text = QVBoxLayout()
        name = QLabel(title_text)
        name.setObjectName("SettingsCardTitle")
        description = QLabel(hint)
        description.setObjectName("Subtitle")
        description.setWordWrap(True)
        text.addWidget(name)
        text.addWidget(description)
        header.addLayout(text, 1)
        outer.addLayout(header)
        content = QVBoxLayout()
        content.setSpacing(10)
        outer.addLayout(content)
        return frame, content

    columns = QHBoxLayout()
    columns.setSpacing(12)
    left_scroll = QScrollArea()
    left_scroll.setWidgetResizable(True)
    left_body = QWidget()
    left_body.setObjectName("SettingsBody")
    left_layout = QVBoxLayout(left_body)
    left_layout.setContentsMargins(0, 0, 0, 0)
    left_layout.setSpacing(12)

    markdown_card, markdown = card("今日计划与资源 Markdown 目录",
        "每日计划、Prompt、Skill 和资源说明保存在这里，可与 Obsidian 共用同一目录。", "▱")
    path_row = QHBoxLayout()
    path_row.addWidget(QLabel("当前目录"))
    window.workbench_location = QLineEdit(str(work_root(window.store)))
    window.workbench_location.setReadOnly(True)
    path_row.addWidget(window.workbench_location, 1)
    path_row.addWidget(button("选择资料文件夹…", window.change_workbench_location))
    markdown.addLayout(path_row)
    path_hint = QLabel("更换位置不会搬移旧资料；原文件会保留在原处。")
    path_hint.setObjectName("Subtitle")
    markdown.addWidget(path_hint)
    left_layout.addWidget(markdown_card)

    backup_card, backup = card("备份目录",
        "保存 Agent 与 myself 的备份文件。使用 U 盘时，通常保留默认位置即可。", "▤")
    backup_row = QHBoxLayout()
    backup_row.addWidget(QLabel("当前目录"))
    window.backup_path = QLineEdit(str(window.service.backup_root()))
    window.backup_path.setPlaceholderText("输入备份目录的完整路径")
    backup_row.addWidget(window.backup_path, 1)
    backup_row.addWidget(button("浏览…", window.change_backup_location))
    backup.addLayout(backup_row)
    backup_actions = QHBoxLayout()
    backup_actions.addWidget(button("打开备份文件夹", lambda: window.open_path(window.service.backup_root())))
    backup_actions.addWidget(button("保存备份目录", window.save_settings, True))
    backup_actions.addStretch(1)
    backup.addLayout(backup_actions)
    backup_hint = QLabel("更改位置只影响之后创建的备份；旧备份不会自动搬移。")
    backup_hint.setObjectName("Subtitle")
    backup.addWidget(backup_hint)
    # Kept as a compatibility field for the existing save handler.
    window.backup_location = QTextEdit(str(window.service.backup_root()))
    window.backup_location.setReadOnly(True)
    window.backup_location.hide()
    left_layout.addWidget(backup_card)

    password_card, password = card("统一备份密码",
        "用于 Agent 与 myself 的加密 .amb 备份；关闭管家后会忘记本次输入。Hermes 原生备份仍使用自己的密钥。", "▣")
    window.common_password_status = QLabel()
    window.common_password_status.setWordWrap(True)
    password.addWidget(window.common_password_status)
    password_actions = QHBoxLayout()
    password_actions.addWidget(button("输入 / 更换密码", window.set_common_password, True))
    password_actions.addWidget(button("忘记本次密码", window.forget_common_password))
    password_actions.addStretch(1)
    password.addLayout(password_actions)
    left_layout.addWidget(password_card)

    options_card, options = card("可选设置与维护",
        "自动备份保留数量和电脑维护工具放在这里，不影响日常工作。", "⚙")
    window.settings_advanced_toggle = QToolButton()
    window.settings_advanced_toggle.setText("自动备份最多保留")
    window.settings_advanced_toggle.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
    window.settings_advanced_toggle.setCheckable(True)
    window.settings_advanced_toggle.setArrowType(Qt.ArrowType.RightArrow)
    options.addWidget(window.settings_advanced_toggle, alignment=Qt.AlignmentFlag.AlignLeft)
    window.settings_advanced = QWidget()
    advanced = QVBoxLayout(window.settings_advanced)
    advanced.setContentsMargins(8, 0, 8, 4)
    advanced.setSpacing(8)
    form = QFormLayout()
    window.backup_keep = QSpinBox()
    window.backup_keep.setRange(1, 100)
    window.backup_keep.setValue(int(window.store.setting("backup_keep", 10)))
    window.backup_keep.setSuffix(" 份")
    form.addRow("每个资源", window.backup_keep)
    advanced.addLayout(form)
    advanced.addWidget(button("保存保留数量", window.save_settings), alignment=Qt.AlignmentFlag.AlignLeft)
    automatic = QLabel("仅在自动备份成功后清理旧版本；自动备份需要在对应 Agent 的登记中开启。")
    automatic.setWordWrap(True)
    automatic.setObjectName("Subtitle")
    advanced.addWidget(automatic)
    options.addWidget(window.settings_advanced)
    window.settings_advanced.hide()
    window.settings_advanced_toggle.toggled.connect(window.toggle_settings_advanced)
    options.addWidget(button("电脑维护与配置迁移…", window.maintenance_tools), alignment=Qt.AlignmentFlag.AlignLeft)
    left_layout.addWidget(options_card)
    left_layout.addStretch(1)
    left_scroll.setWidget(left_body)
    columns.addWidget(left_scroll, 7)

    right = QWidget()
    right.setObjectName("SettingsStatusPanel")
    right_layout = QVBoxLayout(right)
    right_layout.setContentsMargins(0, 0, 0, 0)
    right_layout.setSpacing(12)
    status_card, status = card("当前状态", "只显示重要位置和密码状态。", "✓")
    window.settings_mode_status = QLabel()
    window.settings_data_status = QLabel()
    window.settings_backup_status = QLabel()
    window.settings_password_status = QLabel()
    for widget in (window.settings_mode_status, window.settings_data_status,
                   window.settings_backup_status, window.settings_password_status):
        widget.setObjectName("SettingsStatusTile")
        widget.setWordWrap(True)
        status.addWidget(widget)
    right_layout.addWidget(status_card)
    tips_card, tips = card("提示", "", "i")
    tips_text = QLabel("资料目录可与 Obsidian 共用。\n\n更换资料或备份位置不会迁移已有文件。\n\n换电脑时，请带上备份文件并记住对应密码。")
    tips_text.setWordWrap(True)
    tips_text.setObjectName("Subtitle")
    tips.addWidget(tips_text)
    right_layout.addWidget(tips_card)
    right_layout.addStretch(1)
    right.setMinimumWidth(280)
    right.setMaximumWidth(360)
    columns.addWidget(right, 3)
    layout.addLayout(columns, 1)

    def update_status(*_):
        data_root = Path(window.workbench_location.text()).expanduser()
        backup_root = Path(window.backup_path.text().strip().strip('"')).expanduser()
        portable = bool(window.store.portable_root)
        window.settings_mode_status.setText("运行模式\n" + ("便携模式" if portable else "标准模式") +
            (" · 数据随程序目录保存" if portable else " · 数据保存在当前电脑"))
        window.settings_data_status.setText("资料目录\n" + ("已连接" if data_root.is_dir() else "目录需要检查") + "\n" + str(data_root))
        backup_state = "正常" if backup_root.is_dir() else "首次备份时创建"
        window.settings_backup_status.setText("备份目录\n" + backup_state + "\n" + str(backup_root))
        has_password = bool(window.service.common_password)
        window.settings_password_status.setText("备份密码\n" + ("本次已输入" if has_password else "尚未输入；首次备份时可设置"))

    window.settings_status_update = update_status
    window.workbench_location.textChanged.connect(update_status)
    window.backup_path.textChanged.connect(update_status)
    window.backup_location.setText(str(window.service.backup_root()))
    window.refresh_common_password()
    update_status()
    window.stack.addWidget(page)
