from PySide6.QtCore import Qt
from PySide6.QtWidgets import QFormLayout, QLabel, QLineEdit, QScrollArea, QSpinBox, QTextEdit, QToolButton, QVBoxLayout, QWidget

from .components import FlowLayout


def build_settings(window):
    from .window import button, text_view
    page = QWidget()
    page.setObjectName("SettingsPage")
    layout = QVBoxLayout(page)
    title = QLabel("设置")
    title.setObjectName("Title")
    layout.addWidget(title)
    hint = QLabel("默认就能用。通常不需要改这里。")
    hint.setObjectName("Subtitle")
    layout.addWidget(hint)
    scroll = QScrollArea()
    scroll.setWidgetResizable(True)
    body = QWidget()
    body.setObjectName("SettingsBody")
    fields = QVBoxLayout(body)
    fields.setSpacing(14)
    from ..workbench import work_root
    fields.addWidget(QLabel("今日计划和资源 Markdown 放在这里"))
    window.workbench_location = QLineEdit(str(work_root(window.store)))
    window.workbench_location.setReadOnly(True)
    fields.addWidget(window.workbench_location)
    fields.addWidget(button("选择资料文件夹…", window.change_workbench_location))
    shared = QLabel("默认与项目工作区的 myself 共用；没有工作区时随便携数据保存。选择 Obsidian 知识库内的文件夹，即可编辑同一份文件。更换位置不会搬动已有资料。")
    shared.setWordWrap(True)
    shared.setObjectName("Subtitle")
    fields.addWidget(shared)
    fields.addWidget(QLabel("备份文件放在这里"))
    window.backup_path = QLineEdit(str(window.service.backup_root()), body)
    window.backup_location = QTextEdit()
    window.backup_location.setReadOnly(True)
    window.backup_location.setPlainText(str(window.service.backup_root()))
    window.backup_location.setFixedHeight(76)
    window.backup_path.setPlaceholderText("输入备份目录的完整路径")
    fields.addWidget(window.backup_path)
    actions = FlowLayout()
    actions.addWidget(button("打开备份文件夹", lambda: window.open_path(window.service.backup_root())))
    actions.addWidget(button("浏览…", window.change_backup_location))
    actions.addWidget(button("保存备份目录", window.save_settings, True))
    fields.addLayout(actions)
    note = QLabel("使用 U 盘时，保留默认位置就可以。更改位置只影响以后创建的备份，已有文件保留在原处。")
    note.setWordWrap(True)
    note.setObjectName("Subtitle")
    fields.addWidget(note)
    fields.addSpacing(12)
    fields.addWidget(QLabel("统一备份密码"))
    window.common_password_status = QLabel()
    window.common_password_status.setWordWrap(True)
    fields.addWidget(window.common_password_status)
    passwords = FlowLayout()
    passwords.addWidget(button("输入 / 更换密码", window.set_common_password))
    passwords.addWidget(button("忘记本次密码", window.forget_common_password))
    fields.addLayout(passwords)
    explanation = QLabel("用于 Agent 和 myself 的 .amb 备份。本次打开期间共用，关闭后忘记；旧备份继续使用原密码。Hermes 原生备份沿用现有密钥。")
    explanation.setWordWrap(True)
    explanation.setObjectName("Subtitle")
    fields.addWidget(explanation)
    window.refresh_common_password()

    window.settings_advanced_toggle = QToolButton()
    window.settings_advanced_toggle.setText("清理旧备份（可选）")
    window.settings_advanced_toggle.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
    window.settings_advanced_toggle.setCheckable(True)
    window.settings_advanced_toggle.setArrowType(Qt.ArrowType.RightArrow)
    fields.addWidget(window.settings_advanced_toggle, alignment=Qt.AlignmentFlag.AlignLeft)
    window.settings_advanced = QWidget()
    advanced = QVBoxLayout(window.settings_advanced)
    advanced.setSpacing(14)
    form = QFormLayout()
    window.backup_keep = QSpinBox()
    window.backup_keep.setRange(1, 100)
    window.backup_keep.setValue(int(window.store.setting("backup_keep", 10)))
    window.backup_keep.setSuffix(" 份")
    form.addRow("自动备份最多保留", window.backup_keep)
    advanced.addLayout(form)
    advanced.addWidget(button("保存保留数量", window.save_settings), alignment=Qt.AlignmentFlag.AlignLeft)
    automatic = QLabel("自动备份成功后才清理旧版本。自动备份需要在资料的“编辑”中开启，并保持管家打开。")
    automatic.setWordWrap(True)
    advanced.addWidget(automatic)
    fields.addWidget(window.settings_advanced)
    window.settings_advanced.hide()
    window.settings_advanced_toggle.toggled.connect(window.toggle_settings_advanced)
    fields.addWidget(button("电脑维护…", window.maintenance_tools), alignment=Qt.AlignmentFlag.AlignLeft)
    fields.addStretch()
    scroll.setWidget(body)
    layout.addWidget(scroll, 1)
    window.stack.addWidget(page)
