from PySide6.QtCore import Qt
from PySide6.QtWidgets import QFormLayout, QLabel, QLineEdit, QScrollArea, QSpinBox, QTextEdit, QToolButton, QVBoxLayout, QWidget

from .components import FlowLayout


def build_settings(window):
    from .window import button, text_view
    page = QWidget()
    page.setObjectName("SettingsPage")
    layout = QVBoxLayout(page)
    title = QLabel("设置")
    title.setObjectName("Title")
    layout.addWidget(title)
    hint = QLabel("默认就能用。通常不需要改这里。")
    hint.setObjectName("Subtitle")
    layout.addWidget(hint)
    scroll = QScrollArea()
    scroll.setWidgetResizable(True)
    body = QWidget()
    body.setObjectName("SettingsBody")
    fields = QVBoxLayout(body)
    fields.setSpacing(14)
    fields.addWidget(QLabel("备份文件放在这里"))
    window.backup_path = QLineEdit(str(window.service.backup_root()), body)
    window.backup_path.hide()
    window.backup_location = QTextEdit()
    window.backup_location.setReadOnly(True)
    window.backup_location.setPlainText(str(window.service.backup_root()))
    window.backup_location.setFixedHeight(76)
    fields.addWidget(window.backup_location)
    actions = FlowLayout()
    actions.addWidget(button("打开备份文件夹", lambda: window.open_path(window.service.backup_root())))
    actions.addWidget(button("更改位置", window.change_backup_location))
    fields.addLayout(actions)
    note = QLabel("使用 U 盘时，保留默认位置就可以。更改位置只影响以后创建的备份，已有文件保留在原处。")
    note.setWordWrap(True)
    note.setObjectName("Subtitle")
    fields.addWidget(note)
    fields.addSpacing(12)
    window.settings_advanced_toggle = QToolButton()
    window.settings_advanced_toggle.setText("其他功能（需要时再打开）")
    window.settings_advanced_toggle.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
    window.settings_advanced_toggle.setCheckable(True)
    window.settings_advanced_toggle.setArrowType(Qt.ArrowType.RightArrow)
    fields.addWidget(window.settings_advanced_toggle, alignment=Qt.AlignmentFlag.AlignLeft)
    window.settings_advanced = QWidget()
    advanced = QVBoxLayout(window.settings_advanced)
    advanced.setSpacing(14)
    form = QFormLayout()
    window.backup_keep = QSpinBox()
    window.backup_keep.setRange(1, 100)
    window.backup_keep.setValue(int(window.store.setting("backup_keep", 10)))
    window.backup_keep.setSuffix(" 份")
    form.addRow("自动备份最多保留", window.backup_keep)
    advanced.addLayout(form)
    advanced.addWidget(button("保存保留数量", window.save_settings), alignment=Qt.AlignmentFlag.AlignLeft)
    automatic = QLabel("自动备份成功后才清理旧版本。自动备份需要在资料的“编辑”中开启，并保持管家打开。")
    automatic.setWordWrap(True)
    advanced.addWidget(automatic)
    if window.store.portable_root:
        advanced.addWidget(QLabel("记住备份密码（可选）"))
        window.vault_status = QLabel()
        advanced.addWidget(window.vault_status)
        vault = FlowLayout()
        window.vault_unlock_button = button("设置记忆密码", window.unlock_vault)
        vault.addWidget(window.vault_unlock_button)
        vault.addWidget(button("暂时锁定", window.lock_vault))
        advanced.addLayout(vault)
        window.refresh_vault_status()
        explanation = QLabel("不设置也可以：备份或恢复时手动输入密码。设置后可以记住各份备份的密码；关闭管家会自动锁定，下次用你的总密码解锁。")
        explanation.setWordWrap(True)
        advanced.addWidget(explanation)
    advanced.addWidget(QLabel("电脑维护"))
    tools = FlowLayout()
    for label, action in [("导出登记清单", window.export_config), ("导入登记清单", window.import_config), ("检查这台电脑", window.diagnostics),
                          ("忘记已保存的备份密码", window.remove_secret), ("打开管家资料文件夹", lambda: window.open_path(window.store.root))]:
        tools.addWidget(button(label, action))
    advanced.addLayout(tools)
    window.settings_info = text_view()
    window.settings_info.setMinimumHeight(130)
    window.settings_info.setPlainText("管家资料文件夹：" + str(window.store.root) + "\n\n登记清单只告诉管家资料在哪里，不包含项目和聊天文件。换电脑恢复请用“备份与迁移”。")
    advanced.addWidget(window.settings_info)
    fields.addWidget(window.settings_advanced)
    window.settings_advanced.hide()
    window.settings_advanced_toggle.toggled.connect(window.toggle_settings_advanced)
    fields.addStretch()
    scroll.setWidget(body)
    layout.addWidget(scroll, 1)
    window.stack.addWidget(page)
